(global-set-key (kbd "M-Y") 'yank-pop-forwards)
(global-set-key (kbd "C-l") 'duplicate-line)
(global-set-key (kbd "C-x g") 'magit-status)
(global-set-key (kbd "ESC <up>") 'move-line-up)
(global-set-key (kbd "ESC <down>") 'move-line-down)
(global-set-key (kbd "C-c a g") 'ag)
(global-set-key (kbd "C-c a g") 'ag)
