(setq org-directory "~/Dropbox/org")
(setq org-default-notes-file (concat org-directory "/capture.org"))
(setq org-agenda-files '("~/Dropbox/org"))
(setq org-refile-targets (quote (("~/Dropbox/org/personal.org" :level . 1)
                                 ("~/Dropbox/org/work.org" :level . 1))))
