(setq org-use-speed-commands 1)
(setq org-directory "~/Dropbox/org")
(setq org-default-notes-file (concat org-directory "/capture.org"))
(setq org-agenda-files '("~/Dropbox/org"))
(setq org-refile-targets (quote (("~/Dropbox/org/personal.org" :level . 1)
                                 ("~/Dropbox/org/work.org" :level . 1))))
(require 'org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
