# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

setopt auto_cd
cdpath=($HOME/Projects;$HOME/Projects/customer_portal)

# source config
source $HOME/.env.sh
