call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'sebdah/vim-delve'
Plug 'morhetz/gruvbox'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'tpope/vim-fugitive'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
call plug#end()

" gruvbox conf
autocmd vimenter * ++nested colorscheme gruvbox
set background=dark

set incsearch
set number
set confirm         " confirm instead of requiring !
set nobackup noswapfile
set ignorecase smartcase smartindent smarttab
set showmatch incsearch
set hidden          " allow switch between buffers without saving
set wildmenu        " better command-line completion

inoremap jk <ESC>
vnoremap jk <ESC>
let mapleader = ","

" Enable lsp for go by using gopls
let g:completor_filetype_map = {}
let g:completor_filetype_map.go = {'ft': 'lsp', 'cmd': 'gopls -remote=auto'}"
