lastupdatecheck: 0
recentrepos:
- /home/gewilson/Projects/customer_portal
- /home/gewilson/Projects/middleware/orch-topology-qa
- /home/gewilson/Projects/dotfiles
- /home/gewilson/Projects/orch
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: true
